### ISSUE TITLE
LavaOre no Texture

### ISSUE THREAD

**Issue by HeberonYT** [boredherobrine13/morefuelsmod-1.10#5] opened 2017-06-17 15:52 UTC
Hello
I am using your mod on my server sponge 1.10.2 and the block "Lava Ore" has no texture, hopefully can help me to solve it.
Regards!

morefuelsmod-1.10.x-1.6.0.jar
forge:12.18.3.2281
spongeforge-1.10.2-2281-5.2.0-BETA-2379.jar

![screenshot_6](https://user-images.githubusercontent.com/13698597/27254272-e28803c4-534a-11e7-94fc-480ba29c7609.png)

**Comment by boredhero** [comment] 2017-06-19 01:50
Hey. This is new to my knowledge. I am currently about to embark on a 12 day backpacking trip and am many states away from my home, so I will not be able to immediately fix this issue. However, i would appreicate it if you could try downloading forge 12.18.3.2221 and tell me if the texture issue occurs. I test all builds at launch, and I'm guessing a forge update broke it. I'll fix it in v1.7.0, which will be releasing some time mid-late july probably.

**Comment by HeberonYT** [comment] 2017-06-19 18:04
Thanks for your reply, I installed forge 12.18.3.2221 and the problem continues.
I am sorry to hear that you will not be able to upgrade soon, I really hoped to correct it on my public server. Is it possible to fix it temporarily with a texture pack?
Regards!

**Comment by boredhero** [comment] 2017-07-03 05:02
Hey. I just got off the plane today. After some quick toying around I managed to reproduce the issue, only it occurs for alot more things than just lava ore. It is probably fixable for now with a texture pack but I am otherwise investigating what could be causing this in the first place.

**Comment by HeberonYT** [comment] 2017-07-07 03:28
**Hello!**
Something new?

**Comment by boredhero** [comment] 2017-07-07 04:52
Unfortunately not much progress. I've tried alot of things and I'm convinced I now have to go back and totally redo the render system. I would strongly suggest you make a texture pack as a patch. I actually have no experience with texture pack, but if you need the textures you can find them in this repo under the following path:
morefuelsmod-1.10/src/main/resources/assets/morefuelsmod-1.10.x/textures/

**Comment by HeberonYT** [comment] 2017-07-07 19:43
I have created a temporary resourcepack to solve the problem of broken textures. Just add those of your mod, does not include anything extra.
To work correctly, you should extract the "MoreFuelsMod_Fix_Textures" folder and place it inside `".minecraft/resourcepacks/"`
If you place the .zip file the textures will not work.
Feel free to use it while you give yourself time to update the mod.
http://www.mediafire.com/file/yn8shasx5l48hn8/MoreFuelsMod_Fix_Textures.zip
regards

**Comment by boredhero** [comment] 2017-07-08 02:39
@HeberonYT Thank you so much, I will upload it to CurseForge and credit you. Also, It's good to see we have a working replacement for cauldron in spongeforge now. I hadn't noticed you were using that until just now lol. I missed cauldron.

**Comment by HeberonYT** [comment] 2017-07-08 05:05
You do not have to believe anything, it's your textures.
Kauldron I liked it too much, I still have public servants with kauldron in 1.7.10
But I have been asked for a long time to update to a newer version so I have opened a 1.10.2 server with Sponge Forge. It is quite stable, I thought it was not and that's why I did not decide to do it. But now I see that I can continue to open servers in this version. What you need are variety of plugins, I guess they will never match those of bukkit.

**Comment by boredhero** [comment] 2017-07-08 05:24
@HeberonYT The unfortunate problem is what happened with the DMCA with Bukkit. Ultimately, while no lawsuits really occurred, Mojang failed to defend the Bukkit project. It's why to use spigot now, you have to use BuildTools, so you aren't violating the DMCA. Kauldron was based on Bukkit and died along with Bukkit. No one knows why it wasn't continued with spigot, but the guesses revolve around it being simply too legally complicated. A lot of the people behind the scenes retired after the Bukkit incident because they didn't want the legal nightmare. Also isn't there some kinda plugin compatibility mod for sponge? Like a wrapper for spigot plugins.

**Comment by boredhero** [comment] 2017-09-03 17:22
@HeberonYT Issue fixed as of 1.6.1.

**Closed as completed by boredhero** 2017-09-03 17:22 UTC
Labels: bug
